[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
gloo-net = "0.6.0"
js-sys = "0.3.72"
shared = { version = "0.1.0", path = "../shared" }
wasm-bindgen-futures = "0.4.45"
web-sys = "0.3.72"
yew = { version = "0.21.0", features = ["csr"] }
yew-router = "0.18.0"
