services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: final
    develop:
      watch:
        - action: rebuild
          path: ./backend
    ports:
      - 8765:8000
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: final
    develop:
      watch:
        - action: rebuild
          path: ./frontend
    ports:
      - 8000:80