services:
  backend:
    container_name: backend
    # env_file: backend/.env
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: final
    develop:
      watch:
        - action: rebuild
          path: ./backend
        - action: rebuild
          path: ./shared
    ports:
      - 8161:8161
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_PROTOCOL: $BACKEND_PROTOCOL
        BACKEND_HOST: $BACKEND_HOST
        BACKEND_PORT: $BACKEND_PORT
      target: final
    develop:
      watch:
        - action: rebuild
          path: ./frontend
    ports:
      - 127.0.0.1:8162:80

# The commented out section below is an example of how to define a PostgreSQL
# database that your application can use. `depends_on` tells Docker Compose to
# start the database before your application. The `db-data` volume persists the
# database data between container restarts. The `db-password` secret is used
# to set the database password. You must create `db/password.txt` and add
# a password of your choosing to it before running `docker compose up`.
#     depends_on:
#       db:
#         condition: service_healthy
#   db:
#     image: postgres
#     restart: always
#     user: postgres
#     secrets:
#       - db-password
#     volumes:
#       - db-data:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=example
#       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
#     expose:
#       - 5432
#     healthcheck:
#       test: [ "CMD", "pg_isready" ]
#       interval: 10s
#       timeout: 5s
#       retries: 5
# volumes:
#   db-data:
# secrets:
#   db-password:
#     file: db/password.txt

