services:
  db:
    container_name: db
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
  backend:
    container_name: backend
    env_file: .env
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        BACKEND_IF: $BACKEND_IF
      target: final
    develop:
      watch:
        - action: rebuild
          path: ./backend
        - action: rebuild
          path: ./shared
    ports:
      - 127.0.0.1:8161:8161
    depends_on:
      db:
        condition: service_healthy
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_PROTOCOL: $BACKEND_PROTOCOL
        BACKEND_HOST: $BACKEND_HOST
        BACKEND_PORT: $BACKEND_PORT
      target: final
    develop:
      watch:
        - action: rebuild
          path: ./frontend
    ports:
      - 127.0.0.1:8162:80