[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
iso8601-timestamp = "0.3.2"
serde = { version = "1.0.215", features = ["derive"] }
uuid = { version = "1.11.0", features = ["serde"] }
